2025-03-12 15:13:43,958 INFO    MainThread:1397774 [wandb_setup.py:_flush():67] Current SDK version is 0.19.8
2025-03-12 15:13:43,959 INFO    MainThread:1397774 [wandb_setup.py:_flush():67] Configure stats pid to 1397774
2025-03-12 15:13:43,959 INFO    MainThread:1397774 [wandb_setup.py:_flush():67] Loading settings from /home/rg4827/.config/wandb/settings
2025-03-12 15:13:43,959 INFO    MainThread:1397774 [wandb_setup.py:_flush():67] Loading settings from /scratch/rg4827/hw/dl1/wandb/settings
2025-03-12 15:13:43,959 INFO    MainThread:1397774 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-12 15:13:43,959 INFO    MainThread:1397774 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /scratch/rg4827/hw/dl1/wandb/run-20250312_151343-pdbymyw7/logs/debug.log
2025-03-12 15:13:43,959 INFO    MainThread:1397774 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /scratch/rg4827/hw/dl1/wandb/run-20250312_151343-pdbymyw7/logs/debug-internal.log
2025-03-12 15:13:43,959 INFO    MainThread:1397774 [wandb_init.py:init():761] calling init triggers
2025-03-12 15:13:43,959 INFO    MainThread:1397774 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'data_dir': 'dataset/cifar-10-python/cifar-10-batches-py', 'output_dir': 'outputs/ema400', 'batch_size': 128, 'epochs': 400, 'lr': 0.1, 'model_size': 'medium', 'optimizer': 'sgd', 'scheduler': 'cosine', 'weight_decay': 0.0005, 'device': 'cuda', 'task': 'train', 'activation': 'relu', 'dropout': True, 'test_data': 'dataset/cifar-10-python/cifar-10-batches-py/test_batch', '_wandb': {}}
2025-03-12 15:13:43,959 INFO    MainThread:1397774 [wandb_init.py:init():784] starting backend
2025-03-12 15:13:43,959 INFO    MainThread:1397774 [wandb_init.py:init():788] sending inform_init request
2025-03-12 15:13:43,964 INFO    MainThread:1397774 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-03-12 15:13:43,964 INFO    MainThread:1397774 [wandb_init.py:init():798] backend started and connected
2025-03-12 15:13:43,965 INFO    MainThread:1397774 [wandb_init.py:init():891] updated telemetry
2025-03-12 15:13:43,975 INFO    MainThread:1397774 [wandb_init.py:init():915] communicating run to backend with 90.0 second timeout
2025-03-12 15:13:44,119 ERROR   MainThread:1397774 [wandb_init.py:init():1478] error in wandb.init()
Traceback (most recent call last):
  File "/home/rg4827/.local/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1468, in init
    return wi.init(run_settings, run_config)
  File "/home/rg4827/.local/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 963, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: api: failed sending: POST https://api.wandb.ai/graphql giving up after 1 attempt(s): Post "https://api.wandb.ai/graphql": tls: failed to verify certificate: x509: certificate signed by unknown authority
2025-03-12 15:13:45,120 INFO    MsgRouterThr:1397774 [mailbox.py:close():129] Closing mailbox, abandoning 0 handles.
